### PR TITLE
Adds KeyAuth middleware to authenticate requests

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds a KeyAuth middleware that verifies every request by comparing the `key` querystring parameter with a static list of allowed keys.

The allowed keys list can be provided with the `-keys.file` command-line flag. If not specified, the endpoints will be unsecured - which may be useful for testing - but a warning is printed.

Also, this adds a basic connectivity check immediately after creating the database connection pool that I previously forgot to add.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/measure-saver/7)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-saver/7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[cmd/measure-upload/main.go, line 131 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x98879z_G10TZm8lP:-M9x98879z_G10TZm8lQ:bry32h9) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L131)):*
> ```Go
> 	var keys []string
> 
> 	file, err := os.Open(path)
> ```

`flagx.FileBytes` performs a file read and error handling in the flag processing. It could simplify this function.

If you don't like how flagx.FileBytes serializes with ArgsFromEnv, I can also recommend `flagx.FileBytesArray` which does a better job of managing access to both original file names and contents. I suspect that `flagx.FileBytes` should be changed to do something similar, but that will be tricky.
___
*[cmd/measure-upload/main.go, line 137 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x7FprAICebWEzmnCo:-M9x7FprAICebWEzmnCp:b-5wa6nw) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L137)):*
> ```Go
> 	defer file.Close()
> 
> 	scanner := bufio.NewScanner(file)
> ```

Just thinking out loud: one of the design goals for the locate service is to be able to associate api-keys with contact information or other meta data about the client integration. In this case I'm wondering if it would be helpful for the input file to be structured to include two fields per record i.e. apikey and contact or name? or, perhaps simply to allow comments in the file so the config could be self-contained?
___
*[cmd/measure-upload/main.go, line 144 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x8I0t6u5_QRAiBqvW:-M9x8I0t6u5_QRAiBqvX:b-94fhf4) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L144)):*
> ```Go
> }
> 
> func contains(slice []string, el string) bool {
> ```

If `slice` were a map, the presence check could be inline in the validator. i.e.

```
Validator: func(key string, c echo.Context) (bool, error) {
        _, ok := slice[key]
       return ok, nil
},
```

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-saver/7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cmd/measure-upload/main.go, line 131 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x98879z_G10TZm8lP:-MA1S3H3DaRrAZ5gHHj5:bgap4yb) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L131)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`flagx.FileBytes` performs a file read and error handling in the flag processing. It could simplify this function.

If you don't like how flagx.FileBytes serializes with ArgsFromEnv, I can also recommend `flagx.FileBytesArray` which does a better job of managing access to both original file names and contents. I suspect that `flagx.FileBytes` should be changed to do something similar, but that will be tricky.
</blockquote></details>

Done. Did I use it correctly?
___
*[cmd/measure-upload/main.go, line 137 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x7FprAICebWEzmnCo:-MA1S8Ez7Rj1xrRlixYB:b50t65c) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L137)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just thinking out loud: one of the design goals for the locate service is to be able to associate api-keys with contact information or other meta data about the client integration. In this case I'm wondering if it would be helpful for the input file to be structured to include two fields per record i.e. apikey and contact or name? or, perhaps simply to allow comments in the file so the config could be self-contained?
</blockquote></details>

It now ignores comments (lines starting with `#`) and empty lines.

Regarding client identification, each Chrome Extension will include a mandatory `BrowserID` field and two optional `Notes` and `DeviceType` fields that are meant to identify who the client is and where it's located more precisely (e.g. a specific room in the building?) so I would not make it mandatory to describe the client in the keys file's format. It's still an option, though, since users can add comments to that file now.
___
*[cmd/measure-upload/main.go, line 144 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x8I0t6u5_QRAiBqvW:-MA1S2nQCL2Rgfz3r2_4:b-896fix) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L144)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If `slice` were a map, the presence check could be inline in the validator. i.e.

```
Validator: func(key string, c echo.Context) (bool, error) {
        _, ok := slice[key]
       return ok, nil
},
```
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-saver/7#-:-MA1Vf_cAiR3e_YXz2Nh:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[cmd/measure-saver/main.go, line 107 at r2](https://reviewable.io/reviews/m-lab/measure-saver/7#-MA1VXP5EiCIhjBoSMjR:-MA1VXP5EiCIhjBoSMjS:bndgh5t) ([raw file](https://github.com/m-lab/measure-saver/blob/a391e014b45e2941b3104dfd7084993664c8d8a7/cmd/measure-saver/main.go#L107)):*
> ```Go
> 			Validator: func(key string, c echo.Context) (bool, error) {
> 				_, ok := allowedKeys[key]
> 				return ok, nil
> ```

Ah, so when I proposed a map I was imagining `map[string]struct{}{}` but using a `map[string]bool{}` makes this even simpler:

```
return allowedKeys[key], nil
```
___
*[cmd/measure-saver/main.go, line 111 at r2](https://reviewable.io/reviews/m-lab/measure-saver/7#-MA1V5vuEFSOkpWsoHS_:-MA1V5vuEFSOkpWsoHSa:b-an7ano) ([raw file](https://github.com/m-lab/measure-saver/blob/a391e014b45e2941b3104dfd7084993664c8d8a7/cmd/measure-saver/main.go#L111)):*
> ```Go
> 		}))
> 	} else {
> 		fmt.Println("Warning: no keys file specified. The endpoints will be " +
> ```

Just to be sure -- is this really a deployment model you want to support?
___
*[cmd/measure-upload/main.go, line 131 at r1](https://reviewable.io/reviews/m-lab/measure-saver/7#-M9x98879z_G10TZm8lP:-MA1VGp_38WHjmH6cZo9:bb6mt9b) ([raw file](https://github.com/m-lab/measure-saver/blob/96fb0d5f208a5c5bdee6775810a3c2276ebe4422/cmd/measure-upload/main.go#L131)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done. Did I use it correctly?
</blockquote></details>

:+1:

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-saver/7)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cmd/measure-saver/main.go, line 107 at r2](https://reviewable.io/reviews/m-lab/measure-saver/7#-MA1VXP5EiCIhjBoSMjR:-MA1XKhX9wc-tYmqGEey:b-896fix) ([raw file](https://github.com/m-lab/measure-saver/blob/a391e014b45e2941b3104dfd7084993664c8d8a7/cmd/measure-saver/main.go#L107)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, so when I proposed a map I was imagining `map[string]struct{}{}` but using a `map[string]bool{}` makes this even simpler:

```
return allowedKeys[key], nil
```
</blockquote></details>

Done.
___
*[cmd/measure-saver/main.go, line 111 at r2](https://reviewable.io/reviews/m-lab/measure-saver/7#-MA1V5vuEFSOkpWsoHS_:-MA1XLCz9DzoKtzGQ5SG:boesdfz) ([raw file](https://github.com/m-lab/measure-saver/blob/a391e014b45e2941b3104dfd7084993664c8d8a7/cmd/measure-saver/main.go#L111)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just to be sure -- is this really a deployment model you want to support?
</blockquote></details>

Good question. I left it because it's been useful for testing locally, even if it's definitely a terrible idea for production deployments. I might remove it before the end of this project.

**Pull request merged**
