### PR TITLE
Create handler for /tests and the Measurement model

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds a handler for the `/tests` endpoint and the corresponding Measurement struct representing a JSON-encoded measurement POSTed to `/tests`.

Please note this is part of a set of PRs that I've split for clarity, so e.g. there could be packages that seem unused in `go.mod`.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/measure-upload-service/1)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-upload-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[internal/handlers.go, line 1 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cdaD96S6GpUSY6qgC:-M9cdaD96S6GpUSY6qgD:bcv1n8a) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L1)):*
> ```Go
> package internal
> ```

I felt funny the last time I saw this pattern putting complex logic in the package named `internal`. I think of the `internal` convention in Go being a directory for explicit package names that should be "internal". So, I suggest moving this file content to a package within the `internal` directory.
___
*[internal/handlers.go, line 13 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cdIP73CGk8NzV71Vk:-M9cdIP73CGk8NzV71Vl:bahecg3) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L13)):*
> ```Go
> 
> // TestsHandler is the handler for the /tests endpoint.
> type TestsHandler struct {
> ```

The design doc describes the target resource as `/v0/upload` -- this PR is working with `/test`. I suggest `Upload` is a preferable prefix for several reasons: removes ambiguity with unit tests, is named after the service, it's a verb that describes what is happening.

A candidate package name could be `upload.Handler` if you're open to the suggestion to move this logic into an independent package.
___
*[internal/handlers.go, line 18 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9ce7B2-JJWByJ48II-:-M9ce7B2-JJWByJ48II0:b-50bbpn) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L18)):*
> ```Go
> 
> // CustomValidator is a custom validator wrapping go-playground/validator.
> type CustomValidator struct {
> ```

In a separate package, this could be simply `upload.Validator` -- it would be implicitly "custom".
___
*[internal/handlers_test.go, line 181 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cfgG35uKtIrx1nn1K:-M9cfgG44wdFJWq_WlJj:bpn863q) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers_test.go#L181)):*
> ```Go
> 		wantErr bool
> 	}{
> 		// TODO: Add test cases.
> ```

Add test cases?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-upload-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[internal/handlers.go, line 1 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cdaD96S6GpUSY6qgC:-M9chkDqB78wntn9BK0d:b-896fix) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I felt funny the last time I saw this pattern putting complex logic in the package named `internal`. I think of the `internal` convention in Go being a directory for explicit package names that should be "internal". So, I suggest moving this file content to a package within the `internal` directory.
</blockquote></details>

Done.
___
*[internal/handlers.go, line 13 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cdIP73CGk8NzV71Vk:-M9chl-X9Obfd7_veDsQ:bpv0sly) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The design doc describes the target resource as `/v0/upload` -- this PR is working with `/test`. I suggest `Upload` is a preferable prefix for several reasons: removes ambiguity with unit tests, is named after the service, it's a verb that describes what is happening.

A candidate package name could be `upload.Handler` if you're open to the suggestion to move this logic into an independent package.
</blockquote></details>

Hmm. I see this as a REST API which conventionally has endpoints named after the manipulated resource, pluralized (e.g. `POST /v0/tests` creates a "test" entity, `GET /v0/tests?id=...` retrieves it from the database, etc). I remember the recent conversation we had around "experiments" vs "tests" vs "measurements", so maybe a good compromise would be `/v0/measurements`?
___
*[internal/handlers.go, line 18 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9ce7B2-JJWByJ48II-:-M9cjPufC6xcIEuVh_vJ:b-896fix) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L18)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In a separate package, this could be simply `upload.Validator` -- it would be implicitly "custom".
</blockquote></details>

Done.
___
*[internal/handlers_test.go, line 181 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cfgG35uKtIrx1nn1K:-M9cjRH8AGEcl_dOugIz:b-kiy2yt) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers_test.go#L181)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Add test cases?
</blockquote></details>

I realized that if I test this single `return cv.Validator.Struct(i)` line I would just be testing that the go-playground/validator works in general, which I assume is true since it has its own tests. I already test that it works on our `model.Measurement` as part of the tests of Handler, but I forgot to remove this autogenerated template.

Do you feel like we're missing something by not testing `Validator.Validate(interface{})` explicitly?

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-upload-service/1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[internal/handlers.go, line 13 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cdIP73CGk8NzV71Vk:-M9clEwW7ZEz-ZOjkkbM:b-eko6p7) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers.go#L13)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Hmm. I see this as a REST API which conventionally has endpoints named as the manipulated resource, pluralized (e.g. `POST /v0/tests` creates a "test" entity, `GET /v0/tests?id=...` retrieves it from the database, etc). I remember the recent conversation we had around "experiments" vs "tests" vs "measurements", so maybe a good compromise would be `/v0/measurements`?
</blockquote></details>

`/v0/measurements` lgtm :+1: -- You're right about REST conventions. I must think REST is a little weird, then..
___
*[internal/handlers_test.go, line 181 at r1](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9cfgG35uKtIrx1nn1K:-M9cmldK1NjTdhz_xwKx:b-7nbn1n) ([raw file](https://github.com/m-lab/measure-upload-service/blob/6c6c38ae3acfc7f971bb3301e05b570df0e15071/internal/handlers_test.go#L181)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I realized that if I test this single `return cv.Validator.Struct(i)` line I would just be testing that the go-playground/validator works in general, which I assume is true since it has its own tests. I already test that it works on our `model.Measurement` as part of the tests of Handler, but I forgot to remove this autogenerated template.

Do you feel like we're missing something by not testing `Validator.Validate(interface{})` explicitly?
</blockquote></details>

lgtm.
___
*[internal/measurements/handler_test.go, line 53 at r2](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9coG_RBS3vsp5v3Tpl:-M9coG_RBS3vsp5v3Tpm:biamwur) ([raw file](https://github.com/m-lab/measure-upload-service/blob/10a6647b9b70b61b0ad51b071668777f8c34ab6d/internal/measurements/handler_test.go#L53)):*
> ```Go
> }
> 
> func TestTestsHandler_Post(t *testing.T) {
> ```

`TestTests`?
___
*[internal/measurements/handler_test.go, line 70 at r2](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9coxvz9zKQQuvZ_Tch:-M9coxvz9zKQQuvZ_Tci:b-d3mst1) ([raw file](https://github.com/m-lab/measure-upload-service/blob/10a6647b9b70b61b0ad51b071668777f8c34ab6d/internal/measurements/handler_test.go#L70)):*
> ```Go
> 	t.Run("ok", func(t *testing.T) {
> 		// Send test request.
> 		req := httptest.NewRequest(http.MethodPost, "/tests?appid=test",
> ```

nit: what resource path do you want to use for the test cases?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/measure-upload-service/1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[internal/measurements/handler_test.go, line 53 at r2](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9coG_RBS3vsp5v3Tpl:-M9cpqKWBY6ph35v9HgJ:btvnln6) ([raw file](https://github.com/m-lab/measure-upload-service/blob/10a6647b9b70b61b0ad51b071668777f8c34ab6d/internal/measurements/handler_test.go#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`TestTests`?
</blockquote></details>

:smile: Reading that hurts. It was named TestHandler previously and vscode doesn't rename test methods. Fixed.
___
*[internal/measurements/handler_test.go, line 70 at r2](https://reviewable.io/reviews/m-lab/measure-upload-service/1#-M9coxvz9zKQQuvZ_Tch:-M9cq8U8ABYw_o38CQdO:b-c4btgf) ([raw file](https://github.com/m-lab/measure-upload-service/blob/10a6647b9b70b61b0ad51b071668777f8c34ab6d/internal/measurements/handler_test.go#L70)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: what resource path do you want to use for the test cases?
</blockquote></details>

`/v0/measurements`, even if tests would work with any resource name here since there's no routing involved it's good to be consistent. Thanks!

**Pull request merged**
